services:
  postgis:
    image: postgis
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: mypassword
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - pgnetwork

  generator:
    image: michaelmorningstar/generator:latest
    ports:
      - 7331:7331
    networks:
      - pgnetwork
      - pipelinenetwork
    depends_on:
      - postgis
    environment:
      - STORES_NUMBER=50

  # martin:
  #   image: ghcr.io/maplibre/martin
  #   restart: unless-stopped
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     - DATABASE_URL=postgresql://postgres:mypassword@postgis/osm
  #   depends_on:
  #     - postgis
  #   networks:
  #     - pgnetwork

  # pgadmin:
  #   image: dpage/pgadmin4
  #   depends_on:
  #     - postgis
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: user@domain.com
  #     PGADMIN_DEFAULT_PASSWORD: pgadminpassword
  #   ports:
  #     - 8080:80
  #   networks:
  #     - pgnetwork

  # osm2pgsql:
  #   image: osm2pgsql
  #   environment:
  #     - name=value
  #   depends_on:
  #     - postgis
  #     # - pgadmin
  #   networks:
  #     - pgnetwork
  #   volumes:
  #     - ./PUT-YOUR-DATASET-HERE:/mnt/dataset

volumes:
  pg_data:


networks:
  pgnetwork:
  pipelinenetwork:
    external: true
